### ISSUE TITLE
Add custom ports from additional scrape configs like syslog listener

### ISSUE THREAD

**Issue by mazzy89** [mdegat01/addon-promtail#132]
**Is your feature request related to a problem? Please describe.**

I would like to have Promtail as receiver of syslog logs

**Describe the solution you'd like**

In the additional scrape configs I have enabled syslog listerner. This listens at the port 1541 receiving logs from a forwarder. It is necessary to make this addon aware of this port. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mazzy89** [comment]
This is for instance the additional scrape configs I use:

```yaml
- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:1514
    idle_timeout: 60s
    label_structured_data: yes
    labels:
      job: "syslog"
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
```

In order for a syslog forwarder like `syslog-ng` to send logs to Promtail the port `1514` must be published.

The only port at the moment that is possible to expose is 9080 https://github.com/mdegat01/addon-promtail/blob/main/promtail/config.json#L15 but the purpose of the port is different.
