### ISSUE TITLE
Addon stopped sending/collecting logs

### ISSUE THREAD

**Issue by frli4797** [mdegat01/addon-promtail#223]
**Describe the bug**
This might or might not be related to me going from my old RPi4 hw to a Yellow and also upgrading Homeassistant OS to 10.2. I have a hard time to pinpoint when this happened.

http://loki.mypersonaldomain.com:3100/loki/api/v1/push

**To Reproduce**
1. Configuring the addon with the loki url like this: http://loki.mypersonaldomain.com:3100/loki/api/v1/push. Loki instance is on another machine and confirmed working and reachable.  (This is the configuration made to the addon by me.)
2. Starting addon.
3. Addon starts normally.
4. No logs lines seems to be ingested or posted to loki.

**Expected behavior**
Add-on starts normally but no log files seems to be ingested. Nor transmitted to my Loki instance. 

**Logs**
Debug-level logs
```
grpc_server_max_send_msg_size: 4194304
  grpc_server_max_concurrent_streams: 100
  grpc_server_max_connection_idle: 2562047h47m16.854775807s
  grpc_server_max_connection_age: 2562047h47m16.854775807s
  grpc_server_max_connection_age_grace: 2562047h47m16.854775807s
  grpc_server_keepalive_time: 2h0m0s
  grpc_server_keepalive_timeout: 20s
  grpc_server_min_time_between_pings: 5m0s
  grpc_server_ping_without_stream_allowed: false
  log_format: logfmt
  log_level: debug
  log_source_ips_enabled: false
  log_source_ips_header: ""
  log_source_ips_regex: ""
  log_request_at_info_level_enabled: false
  http_path_prefix: ""
  external_url: ""
  health_check_target: null
  disable: false
client:
  url: ""
  batchwait: 1s
  batchsize: 1048576
  follow_redirects: false
  backoff_config:
    min_period: 500ms
    max_period: 5m0s
    max_retries: 10
  timeout: 10s
  tenant_id: ""
  stream_lag_labels: ""
clients:
- url: http://loki.mypersonaldomain.com:3100/loki/api/v1/push
  batchwait: 1s
  batchsize: 1048576
  follow_redirects: false
  backoff_config:
    min_period: 500ms
    max_period: 5m0s
    max_retries: 10
  timeout: 10s
  tenant_id: ""
  stream_lag_labels: ""
positions:
  sync_period: 10s
  filename: /data/promtail/positions.yaml
  ignore_invalid_yaml: false
scrape_configs:
- job_name: journal
  pipeline_stages:
  - match:
      selector: '{container_name=~"homeassistant|hassio_supervisor"}'
      stages:
      - multiline:
          firstline: ^\x{001b}
  journal:
    max_age: 12h
    json: false
    labels:
      job: systemd-journal
    path: /var/log/journal
  relabel_configs:
  - source_labels: [__journal__systemd_unit]
    separator: ;
    regex: (.*)
    target_label: unit
    replacement: $1
    action: replace
  - source_labels: [__journal__hostname]
    separator: ;
    regex: (.*)
    target_label: nodename
    replacement: $1
    action: replace
  - source_labels: [__journal_syslog_identifier]
    separator: ;
    regex: (.*)
    target_label: syslog_identifier
    replacement: $1
    action: replace
  - source_labels: [__journal_container_name]
    separator: ;
    regex: (.*)
    target_label: container_name
    replacement: $1
    action: replace
  static_configs: []
target_config:
  sync_period: 10s
  stdin: false
limits_config:
  readline_rate: 10000
  readline_burst: 10000
  readline_rate_drop: true
level=info ts=2023-06-04T11:46:02.937566817Z caller=server.go:288 http=[::]:9080 grpc=[::]:45583 msg="server listening on addresses"
level=info ts=2023-06-04T11:46:02.93844613Z caller=main.go:121 msg="Starting Promtail" version="(version=2.6.1, branch=HEAD, revision=6bd05c9)"
level=debug ts=2023-06-04T11:46:04.358253927Z caller=logging.go:76 msg="GET /ready (200) 183.292µs"
level=debug ts=2023-06-04T11:48:04.36709367Z caller=logging.go:76 msg="GET /ready (200) 106.202µs"
```

**Environment (please complete the following information):**

Add-on version:  2.2.0
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend-version: 20230503.3

**Additional context**
This plugin has previously worked fine with this configuration.
